# This file is a template, and might need editing before it works on your project.
# Official docker image.
stages:
  - binaries
  - containers

image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-initializer:
  stage: binaries
  image: 'gcr.io/cloud-builders/go:alpine'
  #env: ["PROJECT_ROOT=github.com/danisla/kubernetes-tproxy"]
  script:
    # tmate
    # pause
    go get ./...
    go install ./cmd/tproxy-initializer/
    find .

contain-sidecar:
  stage: containers
  script:
    - cd sidecar
    - docker build --pull -t "tproxy-sidecar:$CI_COMMIT_REF_SLUG" .
    - docker push "tproxy-sidecar:$CI_COMMIT_REF_SLUG"

contain-initializer:
  stage: containers
  script:
    - docker build -f Dockerfile-initializer --pull -t "tproxy-initializer:$CI_COMMIT_REF_SLUG" .
    - docker push "tproxy-initializer:$CI_COMMIT_REF_SLUG"

contain-podwatch:
  stage: containers
  script:
    - docker build -f Dockerfile-podwatch --pull -t "tproxy-podwatch:$CI_COMMIT_REF_SLUG" .
    - docker push "tproxy-podwatch:$CI_COMMIT_REF_SLUG"

