steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['get', './...']
  env: ["PROJECT_ROOT=github.com/danisla/kubernetes-tproxy"]
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', './cmd/tproxy-podwatch/']
  env: ["PROJECT_ROOT=github.com/danisla/kubernetes-tproxy"]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'Dockerfile-podwatch', '-t', 'gcr.io/$PROJECT_ID/tproxy-podwatch:0.1.0', '.' ]
images:
- 'gcr.io/$PROJECT_ID/tproxy-podwatch:0.1.0'
