apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-deployment
  labels:
    app: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e
  template:
    metadata:
      labels:
        app: e2e
    spec:
      containers:
      - name: e2e
        image: very/e2e:v1.9.4
        command: ["/bin/sleep"]
        args: ["999999999"]
