images:
  pullPolicy: IfNotPresent
  mitmproxy: mitmproxy/mitmproxy:2.0.2
  tproxy_registry: gitlab.ii.coop/cncf
  tproxy_initializer: kubernetes-tproxy/initializer:kubesnoop
  tproxy_podwatch: kubernetes-tproxy/podwatch:kubesnoop
  tproxy_sidecar: kubernetes-tproxy/sidecar:kubesnoop

tproxy:
  useRBAC: false
  useInitializer: false
  hostPort: 8080
  addStandardModeProxy: false
  # blockSvcCIDR: 10.11.240.0/20
  # allowDNS: 10.11.240.10
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi