apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "tproxy.fullname" . }}
  labels:
    app: {{ template "tproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tproxy
spec:
  selector:
    matchLabels:
      app: {{ template "tproxy.name" . }}
      release: {{ .Release.Name }}
      component: tproxy
  template:
    metadata:
      labels:
        app: {{ template "tproxy.name" . }}
        release: {{ .Release.Name }}
        component: tproxy
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 10
{{- if .Values.tproxy.useRBAC }}
      serviceAccountName: {{ template "tproxy.fullname" . }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-podwatch
          image: {{ .Values.images.tproxy_registry }}/{{ .Values.images.tproxy_podwatch }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          args:
            - '-namespace'
            - '{{ .Release.Namespace }}'
            - '-hostPort'
            - '{{ .Values.tproxy.hostPort }}'
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
{{- if .Values.tproxy.addStandardModeProxy }}
        - name: {{ .Chart.Name }}-standard-mode
          image: {{ .Values.images.mitmproxy }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          tty: true
          securityContext:
            runAsUser: 100
          ports:
            - containerPort: 1080
              hostPort: 1080
              protocol: TCP
          command:
            - 'mitmweb'
            - '-p'
            - '1080'
            - '--insecure'
            - '--stream'
            - '4096'
            - '--cert'
            - '*=/opt/mitmproxy-scripts/mitm-kube-apiserver.pem'
            - '-s'
            - /opt/mitmproxy-scripts/mitm-script.py
          volumeMounts:
            - name: mitmproxy-certs
              mountPath: /home/mitmproxy/.mitmproxy
            - name: app-data
              mountPath: /opt/mitmproxy-scripts/
          resources:
{{ toYaml .Values.tproxy.resources | indent 12 }}
{{- end }}
        - name: {{ .Chart.Name }}-tproxy-mode
          image: {{ .Values.images.mitmproxy }}
          tty: true
          securityContext:
            runAsUser: 100
          ports:
            - containerPort: {{ .Values.tproxy.hostPort }}
              hostPort: {{ .Values.tproxy.hostPort }}
              protocol: TCP
          command:
            - 'mitmdump' # change to mitmdump (otherwise you will get out of memory errors) 
            - '-v'
            - '-p'
            - '{{ .Values.tproxy.hostPort }}'
            - '--mode'
            - 'transparent'
            - '--showhost'
            - '--ssl-insecure'
            - '--set'
            - 'stream_large_bodies=4096'
            # - '--save-stream-file'
            # - '/tmp/mitmweb-captures.log'
            - '--certs'
            - '*=/opt/mitmproxy-scripts/mitm-kube-apiserver.pem'
            - '-s'
            - /opt/mitmproxy-scripts/mitm-script.py
          volumeMounts:
            - name: mitmproxy-certs
              mountPath: /home/mitmproxy/.mitmproxy
            - name: app-data
              mountPath: /opt/mitmproxy-scripts/
          resources:
{{ toYaml .Values.tproxy.resources | indent 12 }}
      volumes:
        - name: mitmproxy-certs
          secret:
            secretName: {{ template "tproxy.fullname" . }}-certs

        - name: app-data
          configMap:
            name: {{ template "tproxy.fullname" . }}
            items:
              - key: mitm-script.py
                path: mitm-script.py
              - key: mitm-kube-apiserver.pem
                path: mitm-kube-apiserver.pem


  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
