apiVersion: v1
kind: Secret
metadata:
{{- if .Values.tproxy.accountSecretName }}
  name: {{ .Values.tproxy.accountSecretName }}
{{- else }}
  name: {{ template "tproxy.fullname" . }}-account-secret
{{- end }}
  annotations:
  {{- if .Values.tproxy.accountSecretName }}
    kubernetes.io/service-account.name: {{ .Values.tproxy.accountSecretName }} 
  {{- else }}
    kubernetes.io/service-account.name: {{ template "tproxy.fullname" . }}-account-secret
  {{- end }}
type: kubernetes.io/service-account-token
